// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/bonds/search": {
            "get": {
                "description": "Search bonds by coupon rate and maturity date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bonds"
                ],
                "summary": "Search bonds",
                "parameters": [
                    {
                        "type": "number",
                        "description": "Minimum coupon rate",
                        "name": "minCoupon",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum coupon rate",
                        "name": "maxCoupon",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Maturity before (YYYY-MM-DD)",
                        "name": "maturityBefore",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Maturity after (YYYY-MM-DD)",
                        "name": "maturityAfter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Bond"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/cmsp": {
            "get": {
                "description": "Get all Capital Market Service Providers, filter by type or license date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cmsp"
                ],
                "summary": "List all CMSPs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CMSP type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Licensed before (YYYY-MM-DD)",
                        "name": "licensedBefore",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Licensed after (YYYY-MM-DD)",
                        "name": "licensedAfter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.CMSP"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/cmsp/{id}": {
            "get": {
                "description": "Get a Capital Market Service Provider by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cmsp"
                ],
                "summary": "Get CMSP by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "CMSP ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CMSP"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/portfolio/recommendation": {
            "post": {
                "description": "Get a recommended portfolio allocation based on user profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "portfolio"
                ],
                "summary": "Recommend a portfolio",
                "parameters": [
                    {
                        "description": "Portfolio request body",
                        "name": "profile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.PortfolioRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.PortfolioResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/stocks": {
            "get": {
                "description": "Get all stocks, optionally filter by gainer or loser",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "List all stocks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "gainer or loser",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Stock"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.StandardResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Asset": {
            "type": "object",
            "properties": {
                "Amount": {
                    "type": "number"
                },
                "Name": {
                    "type": "string"
                },
                "Yield": {
                    "type": "number"
                }
            }
        },
        "domain.Bond": {
            "type": "object",
            "properties": {
                "couponRate": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "issuer": {
                    "type": "string"
                },
                "maturityDate": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "domain.CMSP": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "licensedDate": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "plan": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.PortfolioRequest": {
            "type": "object",
            "properties": {
                "initialCapital": {
                    "type": "number"
                },
                "profile": {
                    "type": "string"
                },
                "targetGoal": {
                    "type": "number"
                }
            }
        },
        "domain.PortfolioResponse": {
            "type": "object",
            "properties": {
                "Bond": {
                    "$ref": "#/definitions/domain.Asset"
                },
                "Cash": {
                    "$ref": "#/definitions/domain.Asset"
                },
                "GapToGoal": {
                    "type": "number"
                },
                "GoalMet": {
                    "type": "boolean"
                },
                "Stock": {
                    "$ref": "#/definitions/domain.Asset"
                },
                "TotalReturn": {
                    "type": "number"
                }
            }
        },
        "domain.Stock": {
            "type": "object",
            "properties": {
                "changePercent": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                },
                "volume": {
                    "type": "integer"
                }
            }
        },
        "utils.StandardResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
