definitions:
  domain.APIResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/domain.DerivedYearData'
        type: array
      metadata:
        items:
          $ref: '#/definitions/domain.IndicatorMeta'
        type: array
      source:
        type: string
    type: object
  domain.Asset:
    properties:
      Amount:
        type: number
      Name:
        type: string
      Yield:
        type: number
    type: object
  domain.Bond:
    properties:
      couponRate:
        type: number
      id:
        type: string
      issuer:
        type: string
      maturityDate:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  domain.CMSP:
    properties:
      description:
        type: string
      id:
        type: integer
      licensedDate:
        type: string
      name:
        type: string
      plan:
        type: string
      source:
        type: string
      type:
        type: string
    type: object
  domain.DerivedYearData:
    properties:
      exchange_rate:
        type: number
      foreign_reserves:
        type: number
      gdp_growth:
        type: number
      govt_debt_gdp:
        type: number
      real_interest_rate:
        type: number
      year:
        type: integer
    type: object
  domain.IndicatorMeta:
    properties:
      description:
        type: string
      indicator:
        type: string
      name:
        type: string
      unit:
        type: string
    type: object
  domain.PortfolioRequest:
    properties:
      initialCapital:
        type: number
      profile:
        type: string
      targetGoal:
        type: number
    type: object
  domain.PortfolioResponse:
    properties:
      Bond:
        $ref: '#/definitions/domain.Asset'
      Cash:
        $ref: '#/definitions/domain.Asset'
      GapToGoal:
        type: number
      GoalMet:
        type: boolean
      Stock:
        $ref: '#/definitions/domain.Asset'
      TotalReturn:
        type: number
    type: object
  domain.Stock:
    properties:
      changePercent:
        type: number
      name:
        type: string
      price:
        type: number
      symbol:
        type: string
      volume:
        type: integer
    type: object
  utils.StandardResponse:
    properties:
      data: {}
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
      timestamp:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/bonds/search:
    get:
      consumes:
      - application/json
      description: Search bonds by coupon rate and maturity date
      parameters:
      - description: Minimum coupon rate
        in: query
        name: minCoupon
        type: number
      - description: Maximum coupon rate
        in: query
        name: maxCoupon
        type: number
      - description: Maturity before (YYYY-MM-DD)
        in: query
        name: maturityBefore
        type: string
      - description: Maturity after (YYYY-MM-DD)
        in: query
        name: maturityAfter
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Bond'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.StandardResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.StandardResponse'
      summary: Search bonds
      tags:
      - bonds
  /api/v1/cmsp:
    get:
      consumes:
      - application/json
      description: Get all Capital Market Service Providers, filter by type or license
        date
      parameters:
      - description: CMSP type
        in: query
        name: type
        type: string
      - description: Licensed before (YYYY-MM-DD)
        in: query
        name: licensedBefore
        type: string
      - description: Licensed after (YYYY-MM-DD)
        in: query
        name: licensedAfter
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.CMSP'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.StandardResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.StandardResponse'
      summary: List all CMSPs
      tags:
      - cmsp
  /api/v1/cmsp/{id}:
    get:
      consumes:
      - application/json
      description: Get a Capital Market Service Provider by its ID
      parameters:
      - description: CMSP ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.CMSP'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.StandardResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.StandardResponse'
      summary: Get CMSP by ID
      tags:
      - cmsp
  /api/v1/economic-indicators:
    get:
      consumes:
      - application/json
      description: Retrieve key economic indicators for Ethiopia
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.StandardResponse'
      summary: Get economic indicators
      tags:
      - economic-indicators
  /api/v1/portfolio/recommendation:
    post:
      consumes:
      - application/json
      description: Get a recommended portfolio allocation based on user profile
      parameters:
      - description: Portfolio request body
        in: body
        name: profile
        required: true
        schema:
          $ref: '#/definitions/domain.PortfolioRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.PortfolioResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.StandardResponse'
      summary: Recommend a portfolio
      tags:
      - portfolio
  /api/v1/stocks:
    get:
      consumes:
      - application/json
      description: Get all stocks, optionally filter by gainer or loser
      parameters:
      - description: gainer or loser
        in: query
        name: type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Stock'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.StandardResponse'
      summary: List all stocks
      tags:
      - stocks
swagger: "2.0"
